spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mysql://10.47.108.36:3306/msk_web
    username: msk-web
    password: Msk123
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9090
  context-path: /batch-manager/
