spring:
  configServer:
        environment: test
        modelName: MQ
        configServerUrl: http://10.20.16.152:8888/msk-config-server/api/load/properties
amqp:
    queues[0]: order-create-queue
    queues[1]: order-payment-queue
    queues[2]: order-delivery-queue
server:
  port: 9091
  context-path: /msk-mq-server/
