spring:
  redis:
    database: 12
    host: 10.20.10.105
    port: 6379
    password: Bms123456
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 1000

  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://10.20.10.104:3306/yd-bms
    username: bms
    password: Bms123
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9090
  context-path: /config-server/

