spring:
  redis:
    database: 12
    host: 10.171.246.164
    port: 6379
    password: Admin123#
    pool:
      max-active: 1024
      max-idle: 200
      max-wait: 1000
server:
  port: 9390
  context-path: /msk-print/

config:
  environment: st
  server:
    baseUrl: http://10.171.246.164/msk-config-server/api
    constant: /load/config/constant