spring:
  aop:
    auto: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
  datasource:
    url: jdbc:mysql://10.173.225.18:3306/msk_public_v1
    username: msk-web
    password: Msk123
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 100
    max-idle: 10
    max-wait: 60000
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties:
    dialect: org.hibernate.dialect.MySQL5Dialect
###Config Server相关配置###########
config:
    server:
      environment: st
      url: http://10.171.246.164/msk-config-server/api
      configConstantUrl: /load/config/constant
      sellerModuleName: SELLER
      sellerLoginServerName: QuerySLAccount